{% set name = "daffy" %}
{% set version = "2.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daffy-{{ version }}.tar.gz
  sha256: f1efff571f74821e04ed44d72d8f4fd2afc84f49deafe19a7c1806327beddcac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.18.0
    - pip
  run:
    - python >={{ python_min }}
    - tomli >=2.0.0
    - narwhals >=2.14.0

test:
  imports:
    - daffy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pandas
    - polars
    - pydantic >=2.4.0

about:
  home: https://github.com/vertti/daffy
  summary: Function decorators for DataFrame validation - columns, data types, and row-level validation with Pydantic. Supports Pandas, Polars, Modin, and PyArrow.
  license: MIT
  license_file: LICENSE
  doc_url: https://daffy.readthedocs.io
  dev_url: https://github.com/vertti/daffy

extra:
  recipe-maintainers:
    - vertti
